name: Run commands within a container image

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    container:
      image: alpine:3.19.1

    steps:
      - run: ls /etc/
      - run: uname -a
      - run: cat /etc/os-release
