name: pipeline-test
on:
  workflow_dispatch:
env:
  HELLO_MESSAGE: Hello World!
jobs:
  test:
    runs-on:
      - self-hosted
      - blue
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: checkout
      uses: actions/checkout@v4.1.0
      with:
        repository: zbazztian/coffeeshop
    - name: echo message
      run: echo "${{ env.HELLO_MESSAGE }}"
    - name: Set up JDK 1.11
      uses: actions/setup-java@v4.0.0
      with:
        distribution: zulu
        java-version: '1.11'
        settings-path: "${{ github.workspace }}"
    - name: sh
      shell: bash
      run: mvn test
#     # This item has no matching transformer
#     - sleep:
#       - key: time
#         value:
#           isLiteral: true
#           value: 1
    - name: echo message
      run: echo Done
