name: Pull Request Checks

on:
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        java-version: [11, 19]
        
    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Run Unit Tests
        run: mvn test

  deploy:
    needs: test

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Build container image
        run: |
          echo -n ${{ secrets.CR_PASSWORD }} | docker login -u ${{ secrets.CR_USER }} --password-stdin ${{ secrets.CR_URL }}
          mvn package -DskipTests
          docker build -t "${{ secrets.CR_URL }}/coffeeshop:latest" --push .

      - name: Deploy
        id: deploy
        uses: zbazztian/ecs-deploy-action@v1
        with:
          access_key: ${{ secrets.ACCESS_KEY }}
          secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
          network_conf: ${{ secrets.NETWORK_CONF }}
          task_def: ${{ secrets.TASK_DEF }}
          
      - name: Add comment with link to instance
        run: gh pr comment ${{ github.event.number }} --body "[test instance](http://${{ steps.deploy.outputs.ip }}:8081)"
        env:
          GH_TOKEN: ${{ github.token }}
